version: "3"
services:
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  nodeapp:
    build:
      context: ./node-backend
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongo:27017
    ports:
      - "80:3000"
    links:
      - mongo
  dataimport:  # the actual mongoserver is not started - only its data files are taken
    build:
      context: ./mongoserver
      dockerfile: Dockerfile
    links:
      - mongo
